### ISSUE TITLE
Implement gitchangelog

### ISSUE THREAD

**Issue by ashmastaflash** [cloudpassage-community/vulnerable_image_check#2]
Implement gitchangelog python module, will make changelog easier to produce.

**Comment by jgibbons-cp** [comment]
Implemented using base config from the SDK.  

Changelog
=========


v1.0
----

Fix
~~~
- Will use gitchangelog. [jgibbons-cp]
- Remove dependency on cloned lib and everything other than the version
  and author strings. [jgibbons-cp]

Other
~~~~~
- Update __init__.py location. [jgibbons-cp]
- Implement gitchangelog. [jgibbons-cp]
- Clean up, add support for octobox (e.g. reporting, exit value) and
  stand alone-execution. [jgibbons-cp]
- Gitchangelog. [jgibbons-cp]
- Rm pyc files. [jgibbons-cp]
- Initial push. [jgibbons-cp]
