### ISSUE TITLE
Add a Dockerfile

### ISSUE THREAD

**Issue by ashmastaflash** [cloudpassage-community/vulnerable_image_check#3]
We will use the Dockerfile to build the image in Dockerhub.  Implement multi-stage builds so that failed unit tests will cause the build to break, and not update the image in Dockerhub.

**Comment by ashmastaflash** [comment]
Base image: https://hub.docker.com/r/halotools/python-sdk/

**Comment by jgibbons-cp** [comment]
Added Dockerfile
