### ISSUE TITLE
CSV output to stdout

### ISSUE THREAD

**Issue by ashmastaflash** [cloudpassage-community/vulnerable_image_check#5]
Setting the `OUTPUT_FORMAT` environment variable to `csv` will cause runner.py to produce a base64-encoded CSV to stdout, which contains the following output fields: 

registry, repository, tag, package, package_version, image_digest

**Comment by ashmastaflash** [comment]
This should have integration tests to confirm correct output

**Comment by jgibbons-cp** [comment]
The environment variable OUTPUT_FORMAT set to csv causes running.py to produce and output base64-encoded CSV to stdout with the requested fields.  Need to write the integration tests still.

**Comment by jgibbons-cp** [comment]
Unit test written and added to travis.yml to confirm format.
