### ISSUE TITLE
Optional non-zero exit

### ISSUE THREAD

**Issue by ashmastaflash** [cloudpassage-community/vulnerable_image_check#7]
We want to be able to exit the program with a non-zero exit code if any vulnerabilities are discovered.  This should take the form of an environment variable called `FAIL_ON_CRITICAL`.  If the `FAIL_ON_CRITICAL` environment variable is set, the tool will exit with a status of `1`, in addition to the formatted output that's issued from stdout.

**Comment by jgibbons-cp** [comment]
In the config I set FAIL_ON_CRITICAL to 0.  If there are any critical vulnerabilities I set it to 1 and print them to stdout.  I then set the exit value to 1.
