### ISSUE TITLE
Target specific repos, images, tags for issue retrieval

### ISSUE THREAD

**Issue by ashmastaflash** [cloudpassage-community/vulnerable_image_check#9]
Environment variables to narrow scope of query:
`REGISTRY_NAME`: Registry name
`REPO_NAME`: Repository name
`REPO_TAG`: Repository tag

Any which are unset, or empty strings, will produce a wildcard match against any.  Otherwise, these vars are expected to match exactly.

**Comment by jgibbons-cp** [comment]
Added support for the following variable names REGISTRY_NAME, REPO_NAME, IMAGE_TAG.  If they are populated the query parameter is added.  If they are None or "" it is not so everything related is returned.
